name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and mkdocs
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          export PATH="$HOME/.cargo/bin:$PATH"
          uv venv
          uv pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv run mkdocs gh-deploy --force --clean
